# -*- coding: utf-8 -*-
"""Fonte UNICA das consultas SQL do banco Firebird AG2006.FDB.

Importado tanto pelo dashboard (leitura ao vivo) quanto pelo sync_dados.py
(snapshot para a nuvem) — assim os dois NUNCA divergem. Se precisar ajustar
uma consulta, ajuste so aqui.
"""

SQL_ITENS = """
SELECT
    c.ID AS CONTRATO_ID, c.NUMERO AS NUMERO, c.DATA AS DATA_CONTRATO,
    c.ST_TIPO_ES AS TIPO_ES, c.DATA_CANCELAMENTO AS DATA_CANCELAMENTO,
    c.CD_MOEDA AS CD_MOEDA,
    cli.NOME AS CLIENTE, c.CD_PRODUTOR AS CD_PRODUTOR, prod.NOME AS PRODUTOR,
    sf.DESCRICAO AS SAFRA, c.OBSERVACAO AS OBSERVACAO,
    ci.NR_SEQ_ITEM AS ID_ITEM_CONTRATO, it.DESCRICAO AS PRODUTO,
    ci.CD_UNIDADE AS CD_UNIDADE, um.ABREVIATURA AS UNIDADE,
    ci.QUANTIDADE AS QT_CONTRATADA, ci.VALOR_UNITARIO AS VL_UNITARIO,
    ci.VALOR_TOTAL AS VL_CONTRATADO, ci.DATA_LIMITE_ENTREGA AS DATA_LIMITE,
    ci.STATUS AS ST_ITEM
FROM CONTRATOS c
JOIN CONTRATOS_ITENS ci
       ON ci.CD_USUARIO = c.CD_USUARIO AND ci.NR_SEQUENCIAL = c.NR_SEQUENCIAL
LEFT JOIN PESSOAS cli ON cli.CODIGO = c.CD_CLIENTE
LEFT JOIN PESSOAS prod ON prod.CODIGO = c.CD_PRODUTOR
LEFT JOIN SAFRAS sf ON sf.CODIGO = c.CD_SAFRA
LEFT JOIN ITENS_ESTOQUE it ON it.ID = ci.ID_ITEM
LEFT JOIN UNIDADESMEDIDA um ON um.CODIGO = ci.CD_UNIDADE
"""

SQL_MOVTO = """
SELECT
    mv.ID_CONTRATO_ITEM AS ID_ITEM_CONTRATO, mv.DATA AS DATA_FAT,
    mv.NR_DOCUMENTO AS NR_DOCUMENTO, mv.ID_UNIDADE AS ID_UNIDADE,
    mv.QUANTIDADE AS QT_FAT, mv.VL_TOTAL AS VL_FAT, mv.ID_NOTA_ITEM AS ID_NOTA_ITEM,
    c.ID AS CONTRATO_ID, cli.NOME AS CLIENTE, prod.NOME AS PRODUTOR,
    sf.DESCRICAO AS SAFRA
FROM CONTRATOS_ITENS_MOVTO mv
JOIN CONTRATOS_ITENS ci ON ci.NR_SEQ_ITEM = mv.ID_CONTRATO_ITEM
JOIN CONTRATOS c
       ON c.CD_USUARIO = ci.CD_USUARIO AND c.NR_SEQUENCIAL = ci.NR_SEQUENCIAL
LEFT JOIN PESSOAS cli ON cli.CODIGO = c.CD_CLIENTE
LEFT JOIN PESSOAS prod ON prod.CODIGO = c.CD_PRODUTOR
LEFT JOIN SAFRAS sf ON sf.CODIGO = c.CD_SAFRA
"""

# ----------------------------------------------------------------------
# CONCILIACAO FINANCEIRA (recebiveis dos contratos de venda)
# ----------------------------------------------------------------------
# Titulos a receber em CONTAS_PAG_REC_PARC (OPERACAO_CONTA='R'). O recebido
# (VL_REC_PAG) confere com a soma das baixas em CONTAS_PAG_REC_BAIXA. Ligamos
# o titulo ao contrato por DOIS caminhos e unimos (UNION dedup) p/ cobertura
# maxima — validado: ~529 contratos vs 308 so pela view:
#   1) view oficial  CONTRATOS_PARCELAS -> V_CTR_PARCELA_NF_PARCELA -> CPRP
#   2) pela NF        CONTRATO -> NF -> CONTAS_PAG_REC(ID_NOTA) -> CPRP
SQL_FIN = """
SELECT CONTRATO_ID, NR_SEQ_GEN, NR_PARCELA, DATA_VENCIMENTO, DATA_QUITACAO,
       VL_PARCELA, VL_REC_PAG, CD_MOEDA, NR_DOCUMENTO
FROM (
    SELECT c.ID AS CONTRATO_ID, prp.NR_SEQ_GEN AS NR_SEQ_GEN,
           prp.NR_PARCELA AS NR_PARCELA, prp.DATA_VENCIMENTO AS DATA_VENCIMENTO,
           prp.DATA_QUITACAO AS DATA_QUITACAO, prp.VL_PARCELA AS VL_PARCELA,
           prp.VL_REC_PAG AS VL_REC_PAG, prp.CD_MOEDA AS CD_MOEDA,
           prp.NR_DOCUMENTO AS NR_DOCUMENTO
    FROM CONTRATOS c
    JOIN CONTRATOS_PARCELAS cp
        ON cp.CD_USUARIO = c.CD_USUARIO AND cp.NR_SEQUENCIAL = c.NR_SEQUENCIAL
    JOIN V_CTR_PARCELA_NF_PARCELA v ON v.ID_CONTRATO_PARCELA = cp.NR_SEQ_ITEM
    JOIN CONTAS_PAG_REC_PARC prp ON prp.NR_SEQ_GEN = v.ID_CPRP
    WHERE c.ST_TIPO_ES = 'S' AND prp.OPERACAO_CONTA = 'R'
    UNION
    SELECT c.ID AS CONTRATO_ID, prp.NR_SEQ_GEN AS NR_SEQ_GEN,
           prp.NR_PARCELA AS NR_PARCELA, prp.DATA_VENCIMENTO AS DATA_VENCIMENTO,
           prp.DATA_QUITACAO AS DATA_QUITACAO, prp.VL_PARCELA AS VL_PARCELA,
           prp.VL_REC_PAG AS VL_REC_PAG, prp.CD_MOEDA AS CD_MOEDA,
           prp.NR_DOCUMENTO AS NR_DOCUMENTO
    FROM CONTRATOS c
    JOIN CONTRATOS_ITENS ci
        ON ci.CD_USUARIO = c.CD_USUARIO AND ci.NR_SEQUENCIAL = c.NR_SEQUENCIAL
    JOIN CONTRATOS_ITENS_MOVTO mv ON mv.ID_CONTRATO_ITEM = ci.NR_SEQ_ITEM
    JOIN NOTAS_ITENS nit ON nit.ID = mv.ID_NOTA_ITEM
    JOIN NOTAS n ON n.ID = nit.ID_NOTA
    JOIN CONTAS_PAG_REC pr ON pr.ID_NOTA = n.ID AND pr.OPERACAO_CONTA = 'R'
    JOIN CONTAS_PAG_REC_PARC prp ON prp.CD_PAG_REC = pr.CD_PAG_REC
    WHERE c.ST_TIPO_ES = 'S' AND mv.ID_NOTA_ITEM IS NOT NULL
)
"""

# ----------------------------------------------------------------------
# CONTAS DE DEPOSITO (em quais contas/caixas o dinheiro do contrato entrou)
# ----------------------------------------------------------------------
# Cada parcela recebida tem BAIXAS (CONTAS_PAG_REC_BAIXA.VALOR_PAGO, que soma
# exatamente o VL_REC_PAG). A conta do deposito esta na FORMA do pagamento
# (PAGAMENTOS_FORMAS.CD_LOCAL_PAGAMENTO -> LOCAL_PAGAMENTO.DESCRICAO). Pegamos
# UMA forma representativa por pagamento (a de maior valor) para nao multiplicar
# quando o pagamento tem mais de uma forma. BAIXA_ID permite deduplicar no painel.
#
# Quando o titulo foi baixado por ADIANTAMENTO (forma sem conta direta), seguimos
# o vinculo ate o adiantamento para achar a conta onde a entrada realmente ocorreu:
#   forma.CD_ADIANTAMENTO_VINC -> ADIANTAMENTOS_VINCULOS.NR_SEQ_GEN_VINC
#   -> .NR_SEQ_GEN -> ADIANTAMENTOS.CD_LOC_PAGAMENTO -> LOCAL_PAGAMENTO.
# (Resolve ~99% do que antes ficava "sem conta"; o resto e credito de NF, sem banco.)
SQL_FIN_CONTAS = """
SELECT p.CONTRATO_ID AS CONTRATO_ID,
       b.NR_SEQ_GEN AS BAIXA_ID,
       COALESCE(lp.DESCRICAO, lpa.DESCRICAO) AS CONTA,
       COALESCE(lp.ST_CAIXA_BANCO, lpa.ST_CAIXA_BANCO) AS ST_CAIXA_BANCO,
       b.VALOR_PAGO AS VL_DEPOSITADO,
       pg.DT_PAGAMENTO AS DATA_PAG
FROM (
    SELECT DISTINCT c.ID AS CONTRATO_ID, prp.NR_SEQ_GEN AS NR_SEQ_GEN
    FROM CONTRATOS c
    JOIN CONTRATOS_PARCELAS cp
        ON cp.CD_USUARIO = c.CD_USUARIO AND cp.NR_SEQUENCIAL = c.NR_SEQUENCIAL
    JOIN V_CTR_PARCELA_NF_PARCELA v ON v.ID_CONTRATO_PARCELA = cp.NR_SEQ_ITEM
    JOIN CONTAS_PAG_REC_PARC prp ON prp.NR_SEQ_GEN = v.ID_CPRP
    WHERE c.ST_TIPO_ES = 'S' AND prp.OPERACAO_CONTA = 'R'
    UNION
    SELECT DISTINCT c.ID, prp.NR_SEQ_GEN
    FROM CONTRATOS c
    JOIN CONTRATOS_ITENS ci
        ON ci.CD_USUARIO = c.CD_USUARIO AND ci.NR_SEQUENCIAL = c.NR_SEQUENCIAL
    JOIN CONTRATOS_ITENS_MOVTO mv ON mv.ID_CONTRATO_ITEM = ci.NR_SEQ_ITEM
    JOIN NOTAS_ITENS nit ON nit.ID = mv.ID_NOTA_ITEM
    JOIN NOTAS n ON n.ID = nit.ID_NOTA
    JOIN CONTAS_PAG_REC pr ON pr.ID_NOTA = n.ID AND pr.OPERACAO_CONTA = 'R'
    JOIN CONTAS_PAG_REC_PARC prp ON prp.CD_PAG_REC = pr.CD_PAG_REC
    WHERE c.ST_TIPO_ES = 'S' AND mv.ID_NOTA_ITEM IS NOT NULL
) p
JOIN CONTAS_PAG_REC_BAIXA b ON b.CD_CONTAS_PAG_REC_PARC = p.NR_SEQ_GEN
LEFT JOIN PAGAMENTOS pg ON pg.CD_PAGAMENTO = b.CD_PAGAMENTO
LEFT JOIN (
    SELECT pf.CD_PAGAMENTO AS CD_PAGAMENTO, pf.CD_LOCAL_PAGAMENTO AS CD_LOCAL_PAGAMENTO,
           pf.CD_ADIANTAMENTO_VINC AS CD_ADIANTAMENTO_VINC
    FROM PAGAMENTOS_FORMAS pf
    WHERE pf.NR_SEQ_FORMA = (
        SELECT FIRST 1 pf2.NR_SEQ_FORMA FROM PAGAMENTOS_FORMAS pf2
        WHERE pf2.CD_PAGAMENTO = pf.CD_PAGAMENTO
        ORDER BY pf2.VL_PAGO_LIQ DESC, pf2.NR_SEQ_FORMA)
) fp ON fp.CD_PAGAMENTO = b.CD_PAGAMENTO
LEFT JOIN LOCAL_PAGAMENTO lp ON lp.CD_LOC_PAGAMENTO = fp.CD_LOCAL_PAGAMENTO
LEFT JOIN ADIANTAMENTOS_VINCULOS av ON av.NR_SEQ_GEN_VINC = fp.CD_ADIANTAMENTO_VINC
LEFT JOIN ADIANTAMENTOS adv ON adv.NR_SEQ_GEN = av.NR_SEQ_GEN
LEFT JOIN LOCAL_PAGAMENTO lpa ON lpa.CD_LOC_PAGAMENTO = adv.CD_LOC_PAGAMENTO
"""
